[project]
name = "ocrlmm"
version = "2.0.0"
description = "Skaner PZ do EDI"
requires-python = ">=3.11"
dependencies = [
    "flet==0.85.3",
    "flet-camera",
    "httpx",
    "pillow",
    "thefuzz",
    "python-docx",
    "openpyxl",
]

[tool.flet]
org = "com.ocrlmm"
product = "ocrLmm"
company = "ocrLmm"
copyright = "Copyright (C) 2026"

[tool.flet.app]
path = "."

[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.CAMERA" = true
"android.permission.READ_MEDIA_IMAGES" = true
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true