[project]
name = "OCRTurbo"
version = "2.4.3"
description = "Skaner PZ do EDI i inne"
requires-python = ">=3.11"
dependencies = [
    "flet==0.85.3",
    "flet-camera",
    "httpx",
    "pillow",
    "thefuzz",
    "python-docx",
    "openpyxl",
    "pypdf",
]

[tool.flet]
org = "com.ocrlmm"
product = "ocrLmm"
company = "ocrLmm"
copyright = "Copyright (C) 2026"
build_version = "2.4.3"
build_number = 243

[tool.flet.app]
path = "."

[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.ACCESS_NETWORK_STATE" = true
"android.permission.CAMERA" = true
"android.permission.READ_MEDIA_IMAGES" = true
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true
