name: Zbuduj Flet APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Konfiguracja Java / Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalacja bibliotek i narzędzia Flet
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Budowanie APK dla Androida
        env:
          CI: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yes | flet build apk --project "ocrLmm" --description "Skaner PZ do EDI" -v
          
      - name: Instalacja ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Zmiana ikony aplikacji
        run: |
          NEW_ICON=".github/assets/app_icon.png"
          
          # Sprawdzamy czy plik ikony istnieje, żeby akcja się nie wyłożyła
          if [ -f "$NEW_ICON" ]; then
            magick $NEW_ICON -resize 48x48   build/apk/src/main/res/mipmap-mdpi/ic_launcher.png || true
            magick $NEW_ICON -resize 72x72   build/apk/src/main/res/mipmap-hdpi/ic_launcher.png || true
            magick $NEW_ICON -resize 96x96   build/apk/src/main/res/mipmap-xhdpi/ic_launcher.png || true
            magick $NEW_ICON -resize 144x144 build/apk/src/main/res/mipmap-xxhdpi/ic_launcher.png || true
            magick $NEW_ICON -resize 192x192 build/apk/src/main/res/mipmap-xxxhdpi/ic_launcher.png || true
            echo "Ikony zostały pomyślnie przeskalowane i podmienione!"
          else
            echo "Ostrzeżenie: Nie znaleziono pliku ikony w $NEW_ICON"
          fi
          
      - name: Zapisanie pliku APK jako Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ocrLmm-Android-APK
          path: build/apk/*.apk
